#!/bin/bash

set -e

usage() { echo "Usage: $0 [-p <project name: string>] [-m <module name: string>]" 1>&2; exit 1; }

while getopts ":p:m:" o; do
    case "${o}" in
        p)
            project=${OPTARG}
            ;;
        m)
            module=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${project}" ] || [ -z "${module}" ]; then
    usage
fi

echo "Creating workflow"
cp .github/workflows/example.yml.tpl ".github/workflows/${module}.yml"
sed -i '' -e s/example1\-example2/${module}/g ./.github/workflows/${module}.yml
sed -i '' -e s/example\-project/${project}/g ./.github/workflows/${module}.yml
echo "Workflow created"