#!/usr/bin/env bash

set -e
set -o nounset
set -o pipefail

script_dir=$(cd "$(dirname "$0")" ; pwd -P)
base_url="https://www.ncdc.noaa.gov/cdo-web/api/v2/"


fetch_access_token() {
  access_token=$1
  if [ -z "${access_token}" ]; then
    echo "ACCESS_TOKEN not set. Usage: access_token"
    exit 1
  else
    echo "${ACCESS_TOKEN}"
  fi
}

goal_datasets() {
  pushd "${script_dir}" > /dev/null
    access_token=$(fetch_access_token $1)
    curl -H "token:${access_token}" "${base_url}datasets?limit=42"
  popd > /dev/null
}

TARGET=${1:-}
if type -t "goal_${TARGET}" &>/dev/null; then
  "goal_${TARGET}" ${@:2}
else
  echo "Usage: $0 <goal>

goal:
    datasets            - Gets all datasets
"
  exit 1
fi
